### ISSUE TITLE
It doesn't always break through

### ISSUE THREAD

**Issue by KVPV** [Hypercall/MouseController#1]
I try to use it in the game window, but it works when I move the mouse manually, or press any button.

If you leave everything as it is, and do not move the mouse, these hooks do not work.

I this tested on Windows 10 1909
With the same IL integrity of processes without 
PPL protection, and UIAccess = false.

Any other ideas?

**Comment by Xyrem** [comment]
A better idea to get rid of all usermode hooks is to use assembly and directly inline syscall.
